### ISSUE TITLE
Issues in RMD instructions

### ISSUE THREAD

**Issue by IceAgeEcologist** [NeotomaDB/Workshops#5]
Might add quick instruction on how to create a directory in GitHub.  Its a bit non-intuitive for new users.

**Comment by SimonGoring** [comment]
I've updated the `README` so that it's clearer about (finding instructions for) branching and forking.  Creating a directory happens locally, not on GitHub itself.  This is all finalized in commit ea666144cd31c92c8ac8455970eeaaa1ea03924b.

We might want to revisit the instructions as a group at some point.
